version: '3'

services:
    httpd:
        image: daocloud.io/library/httpd:2.4
        ports:
            - "88:80"
        volumes:
#            - ./apache/conf:/usr/local/apache2/conf:rw
             - /home/docker-com/docker-compose/nginx-apache/apache/conf:/usr/local/apache2/conf
