version: '3'

services:
    web:
        image: nginx:1.15.0-alpine
        ports:
            - "8082:80"
        volumes:
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw
            - ./nginx/logs:/var/log/nginx
        networks:
            - code-network
    php:
        image: php:7.1.1-fpm-alpine
        volumes:
            - ./nginx/html:/usr/share/nginx/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
#8082端口提供外部访问，可以根据实际需要修改
#本地文件路径根据实际情况修改
#php映射路径和站点路径可以保持一直，便于管理
#网络名称"code-network",可以自己定义
